version: '3.4'

x-common-variables: &common-variables
  DATASOURCE_HOST: ${DB_HOST}
  DATASOURCE_USER: ${DB_USER}
  DATASOURCE_PORT: ${DB_PORT}
  DATASOURCE_PASSWORD: ${DB_PASSWORD}
  DATASOURCE_NAME: ${DB_DATABASE}
  DATASOURCE_PRODUCT_MANAGER_PORT: ${PRODUCT_MANAGER_PORT}

x-xxx-common-services-config: &common-services-config
  restart: always

x-kafka-env: &kafka-env
  KAFKA_BROKER_ID: 1
  KAFKA_ADVERTISED_PORT: 9092
  BROKER_ID_COMMAND: "hostname | cut -d'-' -f2"
  KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
  KAFKA_CREATE_TOPICS: "logging:20:1,pushnotifications:10:1,invoicing:10:1,mailing:10:1,userupdates:10:1,orderupdates:10:1"
  KAFKA_LISTENERS: "PLAINTEXT://:9092"
 
services:
  mysqldb:
    image: mysql
    cap_add:
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mystorage:/var/lib/mysql

  productmanager:
    build:
      context: .
      dockerfile: productmanager/Dockerfile
    depends_on:
      - mysqldb
    ports:
      - "3333:3333"
    restart: always
    environment:
      <<: *common-variables

  zoo:
    <<: *common-services-config
    image: library/zookeeper:3.4.13
    environment:
      ZOO_MY_ID: 1

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    <<: *common-services-config
    environment: *kafka-env
    depends_on:
      - zoo

volumes:
  mystorage:
